// <auto-generated />
namespace WebAppIMaster.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class U_ClickHouwDidAboutUs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(U_ClickHouwDidAboutUs));
        
        string IMigrationMetadata.Id
        {
            get { return "201905250625101_U_ClickHouwDidAboutUs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
